- name: "Create local Kubernetes cluster"
  block:
    - name: Use Kind on CI
      when: use_ci | default(false)
      block:
        - name: Install kind CLI
          ansible.builtin.command: >
            curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.25.0/kind-linux-amd64 && chmod +x ./kind && sudo mv ./kind /usr/local/bin/kind
          args:
            creates: /usr/local/bin/kind

        - name: Create Kind cluster
          community.kubernetes.k8s_info:
            kind: Cluster
          ignore_errors: true
          # ou utiliser une commande shell simple si tu n’as pas de module Kind officiel
          # command: kind create cluster --name crypto-cluster --config ../../k8s/kind-config.yaml

    - name: Use Minikube locally
      when: not use_ci
      block:
        - name: Start minikube (docker driver)
          ansible.builtin.command: minikube start --driver=docker
          when: "'Running' not in lookup('pipe', 'minikube status | grep host')"
          ignore_errors: yes

- name: Ensure argocd namespace exists
  community.kubernetes.k8s:
    kubeconfig: /home/runner/.kube/config
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd
