apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: crypto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/hamzablr/backendDashboard:latest
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: pg-app
                  key: conn