apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: crypto
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: localhost:5001/crypto-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: pg-app
                  key: conn
