apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: crypto
stringData:
  POSTGRES_DB: crypto_db
  POSTGRES_USER: crypto_user
  POSTGRES_PASSWORD: crypto_pass
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: crypto
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: pg-secret
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi