apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: crypto
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: crypto
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80