apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: crypto
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: crypto
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
