---
# roles/tls/tasks/main.yml
- name: Ensure /etc/hosts contains crypto.local
  become: yes
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 crypto.local"
    state: present

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: /tmp/crypto.local.key
    size: 2048
    type: RSA
  register: privatekey_result

- name: Generate CSR
  community.crypto.openssl_csr:
    path: /tmp/crypto.local.csr
    privatekey_path: /tmp/crypto.local.key
    common_name: crypto.local
  register: csr_result

- name: Self-sign certificate
  community.crypto.x509_certificate:
    path: /tmp/crypto.local.crt
    privatekey_path: /tmp/crypto.local.key
    csr_path: /tmp/crypto.local.csr
    provider: selfsigned
    days: 365
    subject:
      common_name: crypto.local
  register: cert_result

- name: Create TLS secret in crypto namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: crypto-tls
        namespace: crypto
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ lookup('file', '/tmp/crypto.local.crt') | b64encode }}"
        tls.key: "{{ lookup('file', '/tmp/crypto.local.key') | b64encode }}"
  ignore_errors: yes
