- name: Ensure /etc/hosts contains crypto.local
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 crypto.local"
    state: present

- name: Generate private key
  community.crypto.x509_privatekey:
    path: /tmp/crypto.local.key
    size: 2048
    state: present

- name: Generate CSR
  community.crypto.x509_csr:
    path: /tmp/crypto.local.csr
    privatekey_path: /tmp/crypto.local.key
    common_name: crypto.local
    state: present

- name: Self-sign certificate
  community.crypto.x509_certificate:
    path: /tmp/crypto.local.crt
    privatekey_path: /tmp/crypto.local.key
    csr_path: /tmp/crypto.local.csr
    provider: selfsigned
    days: 365
    state: present

- name: Ensure crypto namespace exists
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: crypto

- name: Create TLS secret in crypto namespace
  community.kubernetes.k8s:
    state: present
    namespace: crypto
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: crypto-tls
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ lookup('file','/tmp/crypto.local.crt') | b64encode }}"
        tls.key: "{{ lookup('file','/tmp/crypto.local.key') | b64encode }}"

- name: Clean temporary files
  ansible.builtin.file:
    path: "/tmp/{{ item }}"
    state: absent
  loop:
    - crypto.local.key
    - crypto.local.csr
    - crypto.local.crt
