- name: Ensure crypto.local in /etc/hosts
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 crypto.local"
    state: present

- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ playbook_dir }}/tmp/crypto.local.key"
    size: 2048

- name: Generate CSR
  community.crypto.openssl_csr:
    path: "{{ playbook_dir }}/tmp/crypto.local.csr"
    privatekey_path: "{{ playbook_dir }}/tmp/crypto.local.key"
    common_name: crypto.local

- name: Self-sign cert
  community.crypto.openssl_certificate:
    path: "{{ playbook_dir }}/tmp/crypto.local.crt"
    privatekey_path: "{{ playbook_dir }}/tmp/crypto.local.key"
    csr_path: "{{ playbook_dir }}/tmp/crypto.local.csr"
    provider: selfsigned
    days: 365

- name: Create/update TLS secret in crypto namespace
  community.kubernetes.k8s:
    state: present
    namespace: crypto
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: crypto-tls
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ lookup('file', playbook_dir + '/tmp/crypto.local.crt') | b64encode }}"
        tls.key: "{{ lookup('file', playbook_dir + '/tmp/crypto.local.key') | b64encode }}"
