- name: Create crypto namespace
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: crypto

- name: Deploy Helm chart
  community.kubernetes.helm:
    name: crypto-dashboard
    chart_ref: ../../helm/crypto-chart
    release_namespace: crypto
    create_namespace: true
    values_file: ../../helm/crypto-chart/values.yaml
    state: present
