- name: Create crypto namespace
  kubernetes.core.k8s:
    name: crypto
    api_version: v1
    kind: Namespace
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3
  environment:
    K8S_AUTH_KUBECONFIG: "/home/runner/.kube/config"

- name: Deploy Helm chart
  community.kubernetes.helm:
    name: crypto-dashboard
    chart_ref: "{{ playbook_dir }}/../../helm/crypto-chart"
    values_files:
      - "{{ playbook_dir }}/../../helm/crypto-chart/values.yaml"
    release_namespace: crypto
    create_namespace: true
    wait: true
    kubeconfig: /home/runner/.kube/config
