name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]   # 1️⃣ Déclenche la pipeline à chaque push sur main
  pull_request:
    branches: [ "main" ]   # 2️⃣ Déclenche aussi sur PR vers main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # === ÉTAPE 1 : Récupération du code source ===
      - name: Checkout repository
        uses: actions/checkout@v3   # 3️⃣ On clone le repo dans la VM runner

      # === ÉTAPE 2 : Setup Docker ===
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2   # 4️⃣ Docker Buildx pour multi-arch

      # === ÉTAPE 3 : Connexion au registry (DockerHub ou GHCR) ===
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # 5️⃣ Utilisation des secrets GitHub
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # === ÉTAPE 4 : Build & Push Backend ===
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./src/backend   # 6️⃣ Construit l’image backend .NET
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crypto-backend:latest

      # === ÉTAPE 5 : Build & Push Frontend ===
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./src/frontend   # 7️⃣ Construit l’image frontend Angular
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crypto-frontend:latest

      # === ÉTAPE 6 : Setup Ansible ===
      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install -y ansible  # 8️⃣ Installe Ansible sur le runner

      # === ÉTAPE 7 : Provisionnement du cluster avec Ansible ===
      - name: Run Ansible playbooks
        run: |
          ansible-playbook ops/ansible/playbooks/setup-cluster.yml       # 9️⃣ Création cluster (kind ou minikube)
          ansible-playbook ops/ansible/playbooks/tls-bootstrap.yml       # 🔟 Certificat + TLS
          ansible-playbook ops/ansible/playbooks/deploy-apps.yml         # 1️⃣1️⃣ Déploiement initial des manifests

      # === ÉTAPE 8 : Setup Kubectl ===
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config      # 1️⃣2️⃣ Injecte le kubeconfig depuis GitHub Secrets

      # === ÉTAPE 9 : Helm Deployment ===
      - name: Deploy with Helm
        run: |
          helm upgrade --install crypto-dashboard ops/helm/crypto-chart \
            --namespace crypto \
            --create-namespace \
            -f ops/helm/crypto-chart/values.yaml                        # 1️⃣3️⃣ Déploiement via Helm (chart custom)

      # === ÉTAPE 10 : Déploiement GitOps avec ArgoCD ===
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd /usr/local/bin/argocd              # 1️⃣4️⃣ Télécharge et installe argocd CLI

      - name: Login to ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure                                               # 1️⃣5️⃣ Connexion à l’instance ArgoCD

      - name: Apply ArgoCD App
        run: |
          kubectl apply -f ops/argocd/app.yaml                        # 1️⃣6️⃣ Déclare l’application dans ArgoCD
          argocd app sync crypto-dashboard                            # 1️⃣7️⃣ Sync pour appliquer les manifests depuis Git

